// <auto-generated />
using System;
using GraphQLDemo.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQLDemo.Migrations
{
    [DbContext(typeof(PlayerContext))]
    [Migration("20210119124032_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("GraphQLDemo.Models.Player", b =>
                {
                    b.Property<Guid?>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = new Guid("2240f17f-97e3-4033-9167-470b0067ac30"),
                            FirstName = "Sergio",
                            LastName = "Ramos"
                        },
                        new
                        {
                            PlayerId = new Guid("ca02eb8e-5124-4b10-a071-948465fc0e0b"),
                            FirstName = "Karim",
                            LastName = "Benzema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
